export const COPY = {
  auth: {
    loginTitle: 'Sign In',
    registerTitle: 'Create Account',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    nameLabel: 'Full Name',
    loginButton: 'Sign In',
    registerButton: 'Create Account',
    loginPrompt: "Don't have an account?",
    registerPrompt: 'Already have an account?',
    loginLink: 'Sign up',
    registerLink: 'Sign in',
  },
  errors: {
    nameRequired: 'Please enter your name.',
    emailRequired: 'Please enter your email.',
    emailInvalid: 'Please enter a valid email address.',
    passwordRequired: 'Please enter your password.',
    passwordMinLength: 'Password must be at least 8 characters.',
    loginFailed: 'Login failed. Please check your email and password.',
    registerFailed: 'Registration failed. Please try again.',
    sessionExpired: 'Your session has expired. Please login again.',
    tasksFailed: 'Failed to load tasks. Please try again.',
    taskSaveFailed: 'Failed to save task. Please check your input.',
    taskDeleteFailed: 'Failed to delete task. Please try again.',
    titleRequired: 'Task title is required.',
  },
  success: {
    taskCreated: 'Task created successfully.',
    taskUpdated: 'Task updated successfully.',
    taskDeleted: 'Task deleted successfully.',
  },
  tasks: {
    pageTitle: 'My Tasks',
    addTask: 'Add Task',
    editTask: 'Edit Task',
    deleteTask: 'Delete Task',
    noTasks: 'No tasks found. Create your first task!',
    filterAll: 'All',
    filterPending: 'Pending',
    filterInProgress: 'In Progress',
    filterDone: 'Done',
    searchPlaceholder: 'Search by title...',
    statusPending: 'Pending',
    statusInProgress: 'In Progress',
    statusDone: 'Done',
    titleLabel: 'Title',
    descriptionLabel: 'Description',
    statusLabel: 'Status',
    deadlineLabel: 'Deadline',
    saveButton: 'Save Task',
    cancelButton: 'Cancel',
    deleteConfirm: 'Are you sure you want to delete this task?',
    deleteConfirmTitle: 'Delete Task',
    deleteButton: 'Delete',
  },
};
